api_platform:
    title: Student Management API
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
            public: true
            max_age: 0
            shared_max_age: 3600
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        pagination_client_enabled: true
        pagination_items_per_page: 20
    collection:
        pagination:
            enabled_parameter_name: pagination
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    name_converter: 'serializer.name_converter.camel_case_to_snake_case'
    mapping:
        paths: ['%kernel.project_dir%/src/Domain/Entity', '%kernel.project_dir%/src/Domain/Dto']
    graphql:
        enabled: true
        graphql_playground: false
    doctrine:
        enabled: true
    eager_loading:
        enabled: true
        max_joins: 30
        force_eager: false