framework:
    cache:
        # Namespace для ключей кэша
        prefix_seed: otus/skill-mentor-service

        # Настройка дефолтного адаптера
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            cache.app.taggable:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                tags: true
            
            group_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                tags: true
                default_lifetime: '%cache_ttl%'