old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        teacher_skills:
            connection: default
            exchange_options:
                name: 'teacher_skills'
                type: direct
        teacher_groups:
            connection: default
            exchange_options:
                name: 'teacher_groups'
                type: direct
        cache_invalidation:
            connection: default
            exchange_options:
                name: 'cache_invalidation'
                type: direct
        student_skills:
            connection: default
            exchange_options:
                name: 'student_skills'
                type: direct
        student_groups:
            connection: default
            exchange_options:
                name: 'student_groups'
                type: direct
        group_skills:
            connection: default
            exchange_options:
                name: 'group_skills'
                type: direct
    consumers:
        teacher_skills:
            connection: default
            exchange_options:
                name: 'teacher_skills'
                type: direct
            queue_options: 
                name: 'teacher_skills'
                routing_key: 'teacher_skills'
            callback: App\Infrastructure\MessageHandler\TeacherSkillsMessageHandler
            qos_options:
                prefetch_size: 0
                prefetch_count: 2  # Сложные операции с БД, небольшой prefetch
                global: false
        teacher_groups:
            connection: default
            exchange_options:
                name: 'teacher_groups'
                type: direct
            queue_options: 
                name: 'teacher_groups'
                routing_key: 'teacher_groups'
            callback: App\Infrastructure\MessageHandler\TeacherGroupsMessageHandler
            qos_options:
                prefetch_size: 0
                prefetch_count: 2  # Сложные операции с БД, небольшой prefetch
                global: false
        student_skills:
            connection: default
            exchange_options:
                name: 'student_skills'
                type: direct
            queue_options: 
                name: 'student_skills'
                routing_key: 'student_skills'
            callback: App\Infrastructure\MessageHandler\StudentSkillsMessageHandler
            qos_options:
                prefetch_size: 0
                prefetch_count: 3
                global: false
        student_groups:
            connection: default
            exchange_options:
                name: 'student_groups'
                type: direct
            queue_options: 
                name: 'student_groups'
                routing_key: 'student_groups'
            callback: App\Infrastructure\MessageHandler\StudentGroupsMessageHandler
            qos_options:
                prefetch_size: 0
                prefetch_count: 3
                global: false
        group_skills:
            connection: default
            exchange_options:
                name: 'group_skills'
                type: direct
            queue_options: 
                name: 'group_skills'
                routing_key: 'group_skills'
            callback: App\Infrastructure\MessageHandler\GroupSkillsMessageHandler
            qos_options:
                prefetch_size: 0
                prefetch_count: 5  # Простые операции
                global: false
        cache_invalidation:
            connection: default
            exchange_options:
                name: 'cache_invalidation'
                type: direct
            queue_options: 
                name: 'cache_invalidation'
                routing_key: 'cache_invalidation'
            callback: App\Infrastructure\MessageHandler\CacheInvalidationMessageHandler
            qos_options:
                prefetch_size: 0
                prefetch_count: 10  # Быстрые операции с кешем
                global: false
        # Dead Letter Queues
        teacher_skills_dead_letter:
            connection: default
            exchange_options:
                name: 'teacher_skills_dlx'
                type: direct
            queue_options:
                name: 'teacher_skills_error'
                routing_key: 'teacher_skills_error'
            callback: App\Infrastructure\MessageHandler\DeadLetter\TeacherSkillsDeadLetterMessageHandler
            qos_options:
                prefetch_size: 0
                prefetch_count: 1
                global: false

        teacher_groups_dead_letter:
            connection: default
            exchange_options:
                name: 'teacher_groups_dlx'
                type: direct
            queue_options:
                name: 'teacher_groups_error'
                routing_key: 'teacher_groups_error'
            callback: App\Infrastructure\MessageHandler\DeadLetter\TeacherGroupsDeadLetterMessageHandler
            qos_options:
                prefetch_size: 0
                prefetch_count: 1
                global: false

        student_skills_dead_letter:
            connection: default
            exchange_options:
                name: 'student_skills_dlx'
                type: direct
            queue_options:
                name: 'student_skills_error'
                routing_key: 'student_skills_error'
            callback: App\Infrastructure\MessageHandler\DeadLetter\StudentSkillsDeadLetterMessageHandler
            qos_options:
                prefetch_size: 0
                prefetch_count: 1
                global: false

        student_groups_dead_letter:
            connection: default
            exchange_options:
                name: 'student_groups_dlx'
                type: direct
            queue_options:
                name: 'student_groups_error'
                routing_key: 'student_groups_error'
            callback: App\Infrastructure\MessageHandler\DeadLetter\StudentGroupsDeadLetterMessageHandler
            qos_options:
                prefetch_size: 0
                prefetch_count: 1
                global: false

        group_skills_dead_letter:
            connection: default
            exchange_options:
                name: 'group_skills_dlx'
                type: direct
            queue_options:
                name: 'group_skills_error'
                routing_key: 'group_skills_error'
            callback: App\Infrastructure\MessageHandler\DeadLetter\GroupSkillsDeadLetterMessageHandler
            qos_options:
                prefetch_size: 0
                prefetch_count: 1
                global: false

        cache_invalidation_dead_letter:
            connection: default
            exchange_options:
                name: 'cache_invalidation_dlx'
                type: direct
            queue_options:
                name: 'cache_invalidation_error'
                routing_key: 'cache_invalidation_error'
            callback: App\Infrastructure\MessageHandler\DeadLetter\CacheInvalidationDeadLetterMessageHandler
            qos_options:
                prefetch_size: 0
                prefetch_count: 1
                global: false
