version: '3.7'

services:

  php-fpm:
    build: docker
    container_name: 'php-container-1'
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginx-container-1'
    working_dir: /app
    ports:
      - '7777:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:15
    ports:
      - 15432:5432
    container_name: 'postgresql-container-1'
    working_dir: /app
    environment:
      POSTGRES_DB: 'skill-progress'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - dump-vol:/app/dump
      - postgresql:/var/lib/postgresql/data

volumes:
  dump-vol:
  postgresql:
