version: '3.7'

services:

  php-fpm:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    container_name: 'otus-php-container-1'
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - postgres
      - rabbitmq

  nginx:
    image: nginx:1.27-alpine
    container_name: 'otus-nginx-container-1'
    working_dir: /app
    ports:
      - '7777:80'
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

  postgres:
    image: postgres:17-alpine
    ports:
      - '15432:5432'
    container_name: 'otus-postgresql-container-1'
    working_dir: /app
    environment:
      POSTGRES_DB: 'skill-progress'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - dump-vol:/app/dump
      - postgresql:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: 'otus-elasticsearch-container-1'
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: 'otus-kibana-container-1'
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: 'otus-graphite-container-1'
    restart: always
    ports:
      - "8000:80"
      - "2003:2003"
      - "2004:2004"
      - "2023:2023"
      - "2024:2024"
      - "8125:8125/udp"
      - "8126:8126"

  grafana:
    image: grafana/grafana
    container_name: 'otus-grafana-container-1'
    restart: always
    ports:
      - "3000:3000"

  memcached:
    image: memcached:latest
    container_name: 'otus-memcached-container-1'
    restart: always
    ports:
      - "11212:11211"

  redis:
    image: redis:alpine
    container_name: 'otus-redis-container-1'
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'otus-rabbit-mq-container-1'
    working_dir: /app
    hostname: rabbit-mq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  supervisor:
    container_name: 'otus-supervisor-container-1'
    build: docker/supervisor
    volumes:
      - ./:/app
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    working_dir: /app
    command: [ "supervisord", "-c", "/etc/supervisor/supervisord.conf" ]

volumes:
  dump-vol:
  postgresql:
