controllers:
    resource:
        path: ../src/Interface/Controller/
        namespace: App\Interface\Controller
    type: attribute

api_controllers:
    resource:
        path: ../src/Interface/Controller/Api/
        namespace: App\Interface\Controller\Api
    type: attribute
    prefix: /api

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger_ui_areas:
    path: /api/doc/{area}
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }