controllers:
    resource:
        path: ../src/Interface/Controller/
        namespace: App\Interface\Controller
    type: attribute

api_controllers:
    resource:
        path: ../src/Interface/Controller/Api/
        namespace: App\Interface\Controller\Api
    type: attribute
    prefix: /api