controllers:
    resource:
        path: ../src/Interface/Controller/
        namespace: App\Interface\Controller
    type: attribute

# Страница для тестов функционала
hello_world:
    path: /hello_world/
    controller: App\Interface\Controller\HelloWorldController::hello