# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Добавление параметров, например
    # app.some_parameter: 'some_value'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'

    App\Application\Doctrine\PostGenerateSchemaEventListener:
        tags:
            - { name: doctrine.event_listener, event: postGenerateSchema }

    # Name Converter
    Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter: ~

    # Репозитории
    App\Infrastructure\Repository\Doctrine\GroupRepository:
        arguments:
            $entity_class: App\Domain\Entity\Group

    App\Infrastructure\Repository\Doctrine\TeacherRepository:
        arguments:
            $entity_class: App\Domain\Entity\Teacher

    App\Infrastructure\Repository\Doctrine\SkillRepository:
        arguments:
            $entity_class: App\Domain\Entity\Skill

    App\Infrastructure\Repository\Doctrine\StudentRepository:
        arguments:
            $entity_class: App\Domain\Entity\Student

    App\Infrastructure\Repository\Doctrine\UserRepository:
        arguments:
            $entity_class: App\Domain\Entity\User

    # Интерфейсы репозиториев
    App\Domain\Repository\TeacherRepositoryInterface:
        alias: App\Infrastructure\Repository\Doctrine\TeacherRepository

    App\Domain\Repository\GroupRepositoryInterface:
        alias: App\Infrastructure\Repository\Doctrine\GroupRepository

    App\Domain\Repository\SkillRepositoryInterface:
        alias: App\Infrastructure\Repository\Doctrine\SkillRepository

    App\Domain\Repository\StudentRepositoryInterface:
        alias: App\Infrastructure\Repository\Doctrine\StudentRepository

    App\Domain\Repository\UserRepositoryInterface:
        alias: App\Infrastructure\Repository\Doctrine\UserRepository

    # Сервисы безопасности
    App\Infrastructure\Security\Provider\TokenUserProvider:
        arguments:
            $user_repository: '@App\Domain\Repository\UserRepositoryInterface'

    # Доменные сервисы
    App\Domain\Service\GroupService:
        arguments:
            $group_repository: '@App\Domain\Repository\GroupRepositoryInterface'
            $skill_repository: '@App\Domain\Repository\SkillRepositoryInterface'

    App\Domain\Service\TeacherService:
        arguments:
            $teacher_repository: '@App\Domain\Repository\TeacherRepositoryInterface'
            $skill_repository: '@App\Domain\Repository\SkillRepositoryInterface'

    App\Domain\Service\StudentService:
        arguments:
            $student_repository: '@App\Domain\Repository\StudentRepositoryInterface'
            $skill_repository: '@App\Domain\Repository\SkillRepositoryInterface'

    App\Domain\Service\SkillService:
        arguments:
            $skill_repository: '@App\Domain\Repository\SkillRepositoryInterface'

    # Интерфейсы сервисов
    App\Domain\Service\GroupServiceInterface:
        alias: App\Domain\Service\GroupService

    App\Domain\Service\TeacherServiceInterface:
        alias: App\Domain\Service\TeacherService

    App\Domain\Service\StudentServiceInterface:
        alias: App\Domain\Service\StudentService

    App\Domain\Service\SkillServiceInterface:
        alias: App\Domain\Service\SkillService

    # API Controllers
    App\Interface\Controller\Api\V1\:
        resource: '../src/Interface/Controller/Api/V1/'
        tags: ['controller.service_arguments']